steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "asia.gcr.io/miloo-phoenix/rasa-chatbot:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "asia.gcr.io/miloo-phoenix/rasa-chatbot:$SHORT_SHA",
        "asia.gcr.io/miloo-phoenix/rasa-chatbot:latest",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/miloo-phoenix/rasa-chatbot:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/miloo-phoenix/rasa-chatbot:latest"]
